services:

  app:
  #lembrar de alterar quando eu criar meu diretório do Docker Hub
    image: seu-usuario-no-dockerhub/creio-app:latest
    container_name: creio_app
    restart: always
    ports:
      - "10122:80" 
    networks:
      - creio_network
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: creio_mysql
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
    volumes:
      - creio_mysql_data:/var/lib/mysql
    networks:
      - creio_network

networks:
  creio_network:
    driver: bridge

volumes:
  creio_mysql_data: